In [17]:
import numpy as np
from numpy import ndarray

In [18]:
def assert_same_shape(output: ndarray, output_grad: ndarray):
    assert output.shape == output_grad.shape, \
    '''
    Two ndarray should have the same shape; instead, first ndarray's shape is {0}
    and second ndarray's shape is {1}.
    '''.format(tuple(output_grad.shape), tuple(output.shape))

def assert_dim(t: ndarray,
               dim: ndarray):
    assert len(t.shape) == dim, \
    '''
    Tensor expected to have dimension {0}, instead has dimension {1}
    '''.format(dim, len(t.shape))


In [19]:
# 1D Convolution
input_1d = np.array([1, 2, 3, 4, 5])
param_1d = np.array([1, 1, 1])

def _pad_1d(inp: ndarray, num: int) -> ndarray:
    z = np.array([0])
    z = np.repeat(z, num)
    return np.concatenate([z, inp, z])

_pad_1d(input_1d, 1)

array([0, 1, 2, 3, 4, 5, 0])

In [20]:
def conv_id(inp: ndarray, param: ndarray) -> ndarray:
    assert_dim(inp, 1)
    assert_dim(param, 1)
    param_len = param.shape[0]
    param_mid = param_len // 2
    inp_pad = _pad_1d(inp, param_mid)
    out = np.zeros(inp.shape)
    for o in range(out.shape[0]):
        for p in range(param_len):
            out[o] += param[p] * inp_pad[o+p]
    assert_same_shape(inp, out)
    return out

conv_id(input_1d, param_1d)

array([ 3.,  6.,  9., 12.,  9.])

In [23]:
input_1d = np.array([1, 2, 3, 4, 5])
param_1d = np.array([1, 1, 1, 1, 1])
_pad_1d(input_1d, 2)

array([0, 0, 1, 2, 3, 4, 5, 0, 0])

In [24]:
conv_id(input_1d, param_1d)

array([ 6., 10., 15., 14., 12.])